version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.9-bullseye
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached # This is for the 'app' service

    command: sleep infinity
    network_mode: service:db
    user: vscode

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
      - ..:/workspace:cached # <--- THIS IS THE CRUCIAL LINE FOR THE 'db' SERVICE
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

volumes:
  mariadb-data: